BankBackend/Models/Card.cs
using System.ComponentModel.DataAnnotations;

namespace BankBackend.Models
{
    public class Card
    {
        [Key]
        public int Id { get; set; }

        public int AccountId { get; set; }
        public string CardNumber { get; set; }
        public int CardPin { get; set; }
    }
}

BankBackend/Controllers/CardsController.cs
using BankBackend.Models;
using Microsoft.AspNetCore.Mvc;
using System.Security.Principal;

namespace BankBackend.Controllers
{
	public class CardsController : Controller
	{
		public IActionResult Index(Account account)
		{

            using (var db = new BankContext())
            {
                var card = db.Cards.Where(c => c.AccountId == account.Id).FirstOrDefault();
                account = db.Accounts.Where(c => c.Id == account.Id).FirstOrDefault();
                
                TempData["card"] = card;
            }

            TempData["account"] = account;


            return View();
		}

		public IActionResult PassAccount(Account account)
		{
			using (var db = new BankContext())
			{
                account = db.Accounts.Where(a => a.Id == account.Id).FirstOrDefault();
            }

            TempData["account"] = account;

            return View("Create");
        }

        public IActionResult Create(Card card)
        {
            using (var db = new BankContext())
            {
                // adds user to the database
                db.Add(card);
                // saves the changes
                db.SaveChanges();
            }

            return RedirectToAction("Index", "Accounts");
        }

        [HttpPost]
        public IActionResult Edit(Account account)
        {
            using (var db = new BankContext())
            {
                var cards = db.Cards.Where(c => c.AccountId == account.Id).FirstOrDefault();
                account = db.Accounts.Where(a => a.Id == account.Id).FirstOrDefault();

                TempData["cards"] = cards;
                TempData["account"] = account;
            }

            return View();
        }

        public IActionResult UpdateDetails(Card card)
        {
            using (var db = new BankContext())
            {
                var cards = db.Cards.Where(c => c.Id == card.Id).FirstOrDefault();
                cards.CardNumber = card.CardNumber;
                cards.CardPin = card.CardPin;
                

                db.SaveChanges();
            }

            return RedirectToAction("Index", "Accounts");
        }
    }
}

BankBackend/Views/Cards/Create.cshtml
@model BankBackend.Models.Card;

@{
	ViewData["Title"] = "Create Account";
	Account account = TempData["account"] as Account;
}

<h1>Create Card for @account.FirstName</h1>

<form asp-action="Create" asp-controller="Cards" method="post">
	<input type="hidden" asp-for="AccountId" value="@account.Id" />

	<div class="form-group col-md-6 col-12">
		<label for="cardNumber">Card Number</label>
		<input type="text" class="form-control" id="cardNumber" placeholder="Card Number" asp-for="CardNumber">
	</div>
	<div class="form-group col-md-6 col-12">
		<label for="cardPin">Card Pin</label>
		<input type="text" class="form-control" id="cardPin" placeholder="Card Pin" asp-for="CardPin">
	</div>
	
	<button type="submit" class="btn btn-primary col-lg-3 col-12 my-3 py-3">Add Card</button>
</form>

BankBackend/Views/Cards/Edit.cshtml
@model BankBackend.Models.Card;

@{
	ViewData["Title"] = "Edit Card";

	Account account = TempData["account"] as Account;
	Card card = TempData["cards"] as Card;
}

<h1>Edit @account.FirstName's Card</h1>

<form asp-action="UpdateDetails" asp-controller="Cards" method="post">
	<input type="hidden" asp-for="Id" value="@card.Id" />

	<div class="form-group col-md-6 col-12">
		<label for="cardNumber">Card Number</label>
		<input type="text" class="form-control" id="cardNumber" placeholder="Card Number" asp-for="CardNumber" value="@card.CardNumber">
	</div>
	<div class="form-group col-md-6 col-12">
		<label for="cardPin">Card Pin</label>
		<input type="text" class="form-control" id="cardPin" placeholder="Card Pin" asp-for="CardPin" value="@card.CardPin">
	</div>
	<button type="submit" class="btn btn-primary col-lg-3 col-12 my-3 py-3">Edit</button>
</form>

<!-- Go Back Button -->
<form asp-action="Index" asp-controller="Cards" method="post">
	<input type="hidden" asp-for="Id" value="@account.Id">
	<button type="submit" class="btn btn-danger col-lg-3 col-12 my-3 py-3">Go Back</button>
</form>

BankBackend/Views/Cards/Index.cshtml
@{
	
	ViewData["Title"] = "Card Details";
	
	Card card = TempData["card"] as Card;
	Account account = TempData["account"] as Account;

}

<h1>@account.FirstName's Card Details</h1>

<div>
	@if(card != null) {

		<h4>Card Holder</h4>
		<p>@account.FirstName @account.LastName</p>

		<h4>Card Number</h4>
		<p>@card.CardNumber</p>

		<h4>Card Pin</h4>
		<p>@card.CardPin</p>

		<!-- Edit button -->
		<form asp-action="Edit" asp-controller="Cards" method="post">
			<input type="hidden" asp-for="@account.Id" value="@account.Id">
			<button type="submit" class="btn btn-primary col-lg-3 col-12 my-3 py-3">Edit</button>
		</form>

	} else {
		<h4>This account has no cards</h4>
	}
	<!-- Go Back Button -->
	<a asp-action="Index" asp-controller="Accounts"><button class="btn btn-danger col-lg-3 col-12 my-3 py-3">Go Back</button></a>

</div>