BankBackend/Models/Account.cs
using System.ComponentModel.DataAnnotations;

namespace BankBackend.Models

{
    public class Account
    {
        [Key]
        public int Id { get; set; }
        public int AccountNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public int Age { get; set; }
        public int Salary { get; set; }
        public int Overdraft { get; set; }
    }
}

BankBackend/Controllers/AccountsController.cs
using BankBackend.Models;
using Microsoft.AspNetCore.Mvc;
using System.Security.Principal;

namespace BankBackend.Controllers
{
    public class AccountsController : Controller
    {
        public IActionResult Index()
        {
            // creates list to hold customer objects
            List<Account> accounts = new List<Account>();
            
            using (var db = new BankContext())
            {
                // gets all customers from database
                accounts = db.Accounts.ToList();
            }


            TempData["accounts"] = accounts;
            
            return View();
        }

        public IActionResult Create()
        {
       
            return View();

            
        }
        [HttpPost]
        public IActionResult Create(Account account)
        {
            
            using (var db = new BankContext())
            {
                // adds user to the database
                db.Add(account);
                // saves the changes
                db.SaveChanges();
                
               
            }


            return RedirectToAction("PassAccount", "Cards", account);
        }

        public IActionResult Search(int searchTerm)
        {
            {
                List<Account> accounts = new List<Account>();

                using (var db = new BankContext())
                {
                    // gets all customers from database
                    accounts = db.Accounts.Where(c => c.AccountNumber == searchTerm).ToList();
                }

                TempData["accounts"] = accounts;

                return View("Index");
            }
        }

        [HttpPost]
        public IActionResult Edit(Account account)
        {
            
            using (var db = new BankContext())
            {
                var accounts = db.Accounts.Where(c => c.Id == account.Id).FirstOrDefault();

                TempData["accounts"] = accounts;
            }

            return View();
            
        }

        public IActionResult UpdateDetails(Account account)
        {
            using (var db = new BankContext())
            {
                var accounts = db.Accounts.Where(a => a.Id == account.Id).FirstOrDefault();
                accounts.AccountNumber = account.AccountNumber;
                accounts.FirstName = account.FirstName;
                accounts.LastName = account.LastName;
                accounts.Address = account.Address;
                accounts.Age = account.Age;
                accounts.Salary = account.Salary;
                db.SaveChanges();
            }
            
            return RedirectToAction("Index");
        }

        public IActionResult Details (Account account)
        {
            using (var db = new BankContext())
            {
                var accounts = db.Accounts.Where(c => c.Id == account.Id).FirstOrDefault();

                TempData["accounts"] = accounts;
            }

            return View();
        }
        
        
        public IActionResult Delete(Account account)
        {
            List<Transaction> trans = new List<Transaction>();
            
            using (var db = new BankContext())
            {
                var acc = db.Accounts.Where(c => c.Id == account.Id).FirstOrDefault();
                var card = db.Cards.Where(c => c.AccountId == account.Id).FirstOrDefault();


                trans = db.Transactions.Where(c => c.AccountId == account.Id).ToList();

                db.Remove(acc);
                db.Remove(card);

                foreach (Transaction t in trans)
                {
                    db.Remove(t);
                }

                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public IActionResult Overdraft()
        {
            List<Account> accounts = new List<Account>();

            using (var db = new BankContext())
            {
                // gets all customers from database
                accounts = db.Accounts.Where(c => c.Salary >= 30000 || c.Overdraft > 0).ToList();
                var defaultOverdrafts = db.Accounts.Where(c => c.Salary >= 30000 && c.Overdraft == 0);                 
                
                foreach (var account in defaultOverdrafts)
                {
                    account.Overdraft = account.Salary / 10;
                }

                db.SaveChanges();
            }

            TempData["accounts"] = accounts;

            return View();
        }
        
        public IActionResult EditOverdraft(Account account)
        {
            using (var db = new BankContext())
            {
                var accounts = db.Accounts.Where(c => c.Id == account.Id).FirstOrDefault();
                
                TempData["accounts"] = accounts;
            }

            return View();
        }

        public IActionResult UpdateOverdraft(Account account)
        {
            using (var db = new BankContext())
            {
                var accounts = db.Accounts.Where(c => c.Id == account.Id).FirstOrDefault();
                accounts.Overdraft = account.Overdraft;
                db.SaveChanges();
            }

            return RedirectToAction("Overdraft");
        }

        public IActionResult OverdraftSearch(string searchTerm)
        {
            {
                List<Account> accounts = new List<Account>();

                using (var db = new BankContext())
                {
                    // gets all customers from database
                    accounts = db.Accounts.Where(c => c.Salary >= 30000 && c.FirstName.ToLower().Contains(searchTerm.ToLower())).ToList();
                }

                TempData["accounts"] = accounts;

                return View("Overdraft");
            }
        }
    }
}

BankBackend/Controllers/TransactionsController.cs
using BankBackend.Models;
using Microsoft.AspNetCore.Mvc;

namespace BankBackend.Controllers
{
    public class TransactionsController : Controller
    {
        public IActionResult Index(Account account)
        {
            List<Transaction> transactions = new List<Transaction>();

            using (var db = new BankContext())
            {
                transactions = db.Transactions.Where(t => t.AccountId == account.Id).ToList();
                account = db.Accounts.Where(c => c.Id == account.Id).FirstOrDefault();
            }

            TempData["transactions"] = transactions;
            TempData["account"] = account;

            return View();
        }

        public IActionResult Create(Account account)
        {
            using (var db = new BankContext())
            {
                account = db.Accounts.Where(a => a.Id == account.Id).FirstOrDefault();
            }

            TempData["account"] = account;

            return View();
        }

        public IActionResult Add(Transaction transaction)
        {
            var account = TempData["account"] as Account;

            using (var db = new BankContext())
            {
                db.Add(transaction);
                db.SaveChanges();

                account = db.Accounts.Where(a => a.Id == transaction.AccountId).FirstOrDefault();
            }


            return RedirectToAction("Index", account);
        }
    }
}

BankBackend/Views/Accounts/Create.cshtml
@model BankBackend.Models.Account;

@{
	ViewData["Title"] = "Create Account";
}

<h1>Add Account</h1>

<form asp-action="Create" asp-controller="Accounts" method="post">

	<div class="form-group col-md-6 col-12">
		<label for="accountNumber">Account Number</label>
		<input type="text" class="form-control" id="accountNumber" placeholder="Account Number" asp-for="AccountNumber">
	</div>
	<div class="form-group col-md-6 col-12">		
		<label for="firstName">First Name</label>
		<input type="text" class="form-control" id="firstName" placeholder="First Name" asp-for="FirstName" >		
	</div>
	<div class="form-group col-md-6 col-12">
		<label for="lastName">Last Name</label>
		<input type="text" class="form-control" id="lastName" placeholder="Last Name" asp-for="LastName">
	</div>
	<div class="form-group col-md-6 col-12">
		<label for="address">Address</label>
		<input type="text" class="form-control" id="address" placeholder="Address" asp-for="Address">
	</div>
	<div class="form-group col-md-6 col-12">
		<label for="age">Age</label>
		<input type="text" class="form-control" id="age" placeholder="Age" asp-for="Age">
	</div>
	<div class="form-group col-md-6 col-12">
		<label for="salary">Salary</label>
		<input type="text" class="form-control" id="salary" placeholder="Salary" asp-for="Salary">
	</div>
	<button type="submit" class="btn btn-primary col-lg-3 col-12 my-3 py-3">Add</button>
</form>

BankBackend/Views/Accounts/Details.cshtml
@{
	ViewData["Title"] = "Details";
	Account account = TempData["accounts"] as Account;
}

<h1>@account.FirstName's Details</h1>


<!-- layout that shows customer data -->
<div>
	
	<h4>Account Number</h4>
	<p>@account.AccountNumber</p>

	<h4>Name</h4>
	<p>@account.FirstName @account.LastName </p>

	<h4>Address</h4>
	<p>@account.Address</p>
	
	<h4>Age</h4>
	<p>@account.Age</p>
	
	<h4>Salary</h4>
	<p>	£@account.Salary</p>

	<!-- Edit button -->
	<form asp-action="Edit" asp-controller="Accounts" method="post">
		<input type="hidden" asp-for="@account.Id" value="@account.Id">
		<button type="submit" class="btn btn-primary col-lg-3 col-12 my-3 py-3">Edit</button>
	</form>

	<!-- Go Back Button -->
	<a asp-action="Index" asp-controller="Accounts"><button class="btn btn-danger col-lg-3 col-12 my-3 py-3">Go Back</button></a>

</div>

BankBackend/Views/Accounts/Edit.cshtml
@model BankBackend.Models.Account;


@{
	ViewData["Title"] = "Account Details";

	Account account = TempData["accounts"] as Account;
}

<h1>@account.FirstName's Details</h1>

<form action="/Accounts/UpdateDetails" method="post">
	<input type="hidden" asp-for="Id" value="@account.Id"/>
	<div class="form-group col-md-6 col-12">
		<label for="accountNumber">Account Number</label>
		<input type="text" class="form-control" id="accountNumber" placeholder="Account Number" asp-for="AccountNumber" value="@account.AccountNumber">
	</div>
	<div class="form-group col-md-6 col-12">
		<label for="firstName">First Name</label>
		<input type="text" class="form-control" id="firstName" placeholder="First Name" asp-for="FirstName" value="@account.FirstName">
	</div>
	<div class="form-group col-md-6 col-12">
		<label for="lastName">Last Name</label>
		<input type="text" class="form-control" id="lastName" placeholder="Last Name" asp-for="LastName" value="@account.LastName">
	</div>
	<div class="form-group col-md-6 col-12">
		<label for="address">Address</label>
		<input type="text" class="form-control" id="address" placeholder="Address" asp-for="Address" value="@account.Address">
	</div>
	<div class="form-group col-md-6 col-12">
		<label for="age">Age</label>
		<input type="text" class="form-control" id="age" placeholder="Age" asp-for="Age" value="@account.Age">
	</div>
	<div class="form-group col-md-6 col-12">
		<label for="salary">Salary</label>
		<input type="text" class="form-control" id="salary" placeholder="Salary" asp-for="Salary" value="@account.Salary">
	</div>
	<button type="submit" class="btn btn-primary col-lg-3 col-12 my-3 py-3">Submit</button>	
</form>

<!-- Go Back Button -->
<form asp-action="Details" asp-controller="Accounts" method="post">
	<input type="hidden" asp-for="Id" value="@account.Id">
	<button type="submit" class="btn btn-danger col-lg-3 col-12 my-3 py-3">Go Back</button>
</form>

BankBackend/Views/Accounts/EditOverdraft.cshtml
@model BankBackend.Models.Account;


@{
	ViewData["Title"] = "Edit Overdraft";

	Account account = TempData["accounts"] as Account;
}

<h1>@account.FirstName's Overdraft</h1>

<form action="/Accounts/UpdateOverdraft" method="post">
	<input type="hidden" asp-for="Id" value="@account.Id" />
	<div class="form-group col-md-6 col-12">
		<label for="overdraft">Overdraft limit</label>
		<input type="text" class="form-control" id="overdraft" placeholder="Overdraft" asp-for="Overdraft" value="@account.Overdraft">
	</div>
	
	<button type="submit" class="btn btn-primary col-lg-3 col-12 my-3 py-3">Submit</button>
</form>

<!-- Go Back Button -->
<form asp-action="Overdraft" asp-controller="Accounts" method="post">
	<input type="hidden" asp-for="Id" value="@account.Id">
	<button type="submit" class="btn btn-danger col-lg-3 col-12 my-3 py-3">Go Back</button>
</form>

BankBackend/Views/Accounts/Index.cshtml
@model BankBackend.Models.Account;
@{
	ViewData["Title"] = "View Accounts";

	// gets list of customer objects sent by the controller
	List<Account> accounts = TempData["accounts"] as List<Account>;
}

<div class="container">
	@if(accounts != null) {
		<div class="row">
			<div class="col-md-12">
				<div class="d-flex align-items-center justify-content-between">
					
					<h1 class="py-3">Accounts</h1>
					
				
					<!-- Search bar -->										
					<form class="d-flex" style="height: 50%" action="/Accounts/Search" method="post">
						<input class="form-control me-1" type="search" placeholder="Search" name="searchTerm">
						<button class="btn btn-primary" type="submit">Search</button>
					</form>
					

				</div>
				
				<table class="table table-striped">
					<thead>
						<tr>	
							<th>Account Number</th>
							<th>First Name</th>
							<th>Actions</th>						
						</tr>
					</thead>
					<tbody>
						@foreach (Account account in accounts)
						{
							<tr>		
								<td>@account.AccountNumber</td>
								<td>@account.FirstName</td>	
								<td class="d-flex justify-content-between align-items-center">
									<!-- View details button -->
									<form asp-action="Details" asp-controller="Accounts" method="post">
										<input type="hidden" asp-for="Id" value="@account.Id">
										<button type="submit" class="btn btn-secondary">Customer Details</button>
									</form>

									<!-- Card details button -->
									<form asp-action="Index" asp-controller="Cards" method="post">
										<input type="hidden" asp-for="Id" value="@account.Id">
										<button type="submit" class="btn btn-warning">Card Details</button>
									</form>

									<!-- Transactions button -->
									<form asp-action="Index" asp-controller="Transactions" method="post">
										<input type="hidden" asp-for="Id" value="@account.Id">
										<button type="submit" class="btn btn-success">Transactions</button>
									</form>
									
									<!-- Delete user button -->
									<form asp-action="Delete" asp-controller="Accounts" method="post">
										<input type="hidden" asp-for="Id" value="@account.Id">
										<button type="submit" class="btn btn-danger">Delete</button>
									</form> 																		
									
								</td>							
							</tr>
						}
					</tbody>
				</table>
			</div>
		</div>
	}
</div>

BankBackend/Views/Accounts/Overdraft.cshtml
@model BankBackend.Models.Account;
@{
	ViewData["Title"] = "View Overdrafts";
	
	// gets list of customer objects sent by the controller
	List<Account> accounts = TempData["accounts"] as List<Account>;
}



<div class="container">
	@if (accounts != null)
	{
		<div class="row">
			<div class="col-md-12">

				<div class="d-flex align-items-center justify-content-between">
					<h1 class="py-3">Account Overdraft</h1>
					
					<form class="d-flex" style="height: 50%" action="/Accounts/OverdraftSearch" method="post">
						<input class="form-control me-1" type="search" placeholder="Search" name="searchTerm">
						<button class="btn btn-primary" type="submit">Search</button>
					</form>
					
				</div>

				<table class="table table-striped">
					<thead>
						<tr>
							<th>Account Number</th>
							<th>First Name</th>							
							<th>Salary</th>
							<th>Overdraft</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						@foreach (Account account in accounts)
						{
							<tr>
								<td>@account.AccountNumber</td>
								<td>@account.FirstName</td>
								<td>£@account.Salary</td>
								<td>£@account.Overdraft</td>
								<td class="d-flex justify-content-between align-items-center">									
									<!-- Change Overdraft button -->
									<form asp-action="EditOverdraft" asp-controller="Accounts" method="post">
										<input type="hidden" asp-for="Id" value="@account.Id">
										<button type="submit" class="btn btn-primary">Edit</button>
									</form>

								</td>
							</tr>
						}
					</tbody>
				</table>
			</div>
		</div>
	}
</div>